
CREATE TABLE IF NOT EXISTS users (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 name TEXT NOT NULL,
 email TEXT UNIQUE NOT NULL,
 password_hash TEXT NOT NULL,
 role TEXT NOT NULL DEFAULT 'customer',
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS products (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 name TEXT NOT NULL,
 category TEXT NOT NULL,
 size_options TEXT NOT NULL DEFAULT 'S,M,L,XL',
 color TEXT NOT NULL DEFAULT 'Black',
 price INTEGER NOT NULL,
 mrp INTEGER NOT NULL,
 rating REAL NOT NULL DEFAULT 0,
 emoji TEXT DEFAULT '👕',
 image TEXT DEFAULT '',
 gallery TEXT DEFAULT '',
 stock INTEGER NOT NULL DEFAULT 0,
 description TEXT DEFAULT '',
 badge_text TEXT DEFAULT 'Ashwini Choice',
 offer_text TEXT DEFAULT '',
 offer_discount REAL DEFAULT 0,
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS orders (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 user_id INTEGER,
 total INTEGER NOT NULL,
 status TEXT NOT NULL DEFAULT 'PAYMENT_PENDING',
 payment_status TEXT NOT NULL DEFAULT 'PENDING',
 payment_method TEXT NOT NULL DEFAULT 'RAZORPAY',
 razorpay_order_id TEXT,
 razorpay_payment_id TEXT,
 razorpay_signature TEXT,
 address TEXT NOT NULL,
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS order_items (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 order_id INTEGER NOT NULL,
 product_id INTEGER NOT NULL,
 size TEXT NOT NULL,
 quantity INTEGER NOT NULL,
 unit_price INTEGER NOT NULL,
 FOREIGN KEY(order_id) REFERENCES orders(id),
 FOREIGN KEY(product_id) REFERENCES products(id)
);

CREATE TABLE IF NOT EXISTS product_reviews (
 id INTEGER PRIMARY KEY AUTOINCREMENT, product_id INTEGER NOT NULL, user_id INTEGER NOT NULL, rating INTEGER NOT NULL CHECK(rating BETWEEN 1 AND 5), feedback TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS product_highlights (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL, value TEXT NOT NULL, active INTEGER DEFAULT 1, sort_order INTEGER DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS returns (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 order_id INTEGER NOT NULL,
 user_id INTEGER NOT NULL,
 reason TEXT NOT NULL,
 request_type TEXT NOT NULL DEFAULT 'REPLACEMENT',
 replacement_size TEXT DEFAULT '',
 replacement_color TEXT DEFAULT '',
 pickup_at TEXT DEFAULT '',
 admin_note TEXT DEFAULT '',
 status TEXT NOT NULL DEFAULT 'REQUESTED',
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);
