import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import vm from 'node:vm';
import fs from 'node:fs';
import {normalizeAddressParts,readAddressParts} from '../scripts/address-parts.js';
const source=fs.readFileSync(new URL('../server.js',import.meta.url),'utf8');
function setup(){const db=new DatabaseSync(':memory:');db.exec("CREATE TABLE saved_delivery_addresses(user_id INTEGER PRIMARY KEY,name TEXT,phone TEXT,address_line TEXT,city TEXT,state TEXT,pincode TEXT,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)");const migration=source.split('\n').find(x=>x.startsWith("if(!db.prepare('PRAGMA table_info(saved_delivery_addresses)"));const routes={};const c={db,normalizeAddressParts,readAddressParts,auth(){},lookupPostalPin:async()=>({city:'Delhi',district:'Delhi',state:'Delhi'}),app:{get:(url,...h)=>routes.get=h.at(-1),put:(url,...h)=>routes.put=h.at(-1)}};vm.createContext(c);vm.runInContext(migration,c);vm.runInContext(migration,c);for(const start of ["app.get('/api/me/delivery-address'","app.put('/api/me/delivery-address'",'function saveDeliveryAddressFromOrder'])vm.runInContext(source.split('\n').find(x=>x.startsWith(start)),c);return {db,c,routes}}
const parts={house:'Flat 4, Building A',street:'Main Road',area:'Central Area',landmark:'Near Park'};
const body={name:'Test Customer',phone:'9876543210',parts,city:'Delhi',state:'Delhi',pincode:'110001'};
async function put(x,b=body,id=1){let result,status=200;await x.routes.put({user:{id},body:b},{status(n){status=n;return this},json(v){result=v}});return {result,status}}
test('structured fields with commas save and reopen exactly',async()=>{const x=setup(),r=await put(x);assert.equal(r.status,200);assert.deepEqual(r.result.address.parts,parts);assert.equal(r.result.address.address_line,'Flat 4, Building A, Main Road, Central Area, Near Park')});
test('legacy address survives schema upgrade and remains readable',async()=>{const x=setup();const r=await put(x,{...body,parts:undefined,address_line:'Old house / lane near school'});assert.equal(r.status,200);assert.equal(r.result.address.parts,null);assert.equal(r.result.address.address_line,'Old house / lane near school')});
test('overlength structured address does not overwrite saved data',async()=>{const x=setup();await put(x);const r=await put(x,{...body,parts:{...parts,street:'x'.repeat(501)}});assert.equal(r.status,400);assert.equal(readAddressParts(x.db.prepare('SELECT * FROM saved_delivery_addresses WHERE user_id=1').get()).parts.street,'Main Road')});
test('order autosave retains parts for same address; clears them for changed address',async()=>{const x=setup(),r=await put(x);const order={delivery_name:body.name,customer_phone:body.phone,delivery_address_line:r.result.address.address_line,delivery_city:'Delhi',delivery_state:'Delhi',delivery_pincode:'110001'};x.c.saveDeliveryAddressFromOrder(1,order);assert.deepEqual(readAddressParts(x.db.prepare('SELECT * FROM saved_delivery_addresses WHERE user_id=1').get()).parts,parts);order.delivery_address_line='Different house and lane';x.c.saveDeliveryAddressFromOrder(1,order);assert.equal(readAddressParts(x.db.prepare('SELECT * FROM saved_delivery_addresses WHERE user_id=1').get()).parts,null)});
test('different customer saved address stays separate',async()=>{const x=setup();await put(x);await put(x,{...body,parts:{...parts,house:'House 99'}},2);assert.equal(readAddressParts(x.db.prepare('SELECT * FROM saved_delivery_addresses WHERE user_id=1').get()).parts.house,parts.house)});
test('saved structured address fills existing checkout fields',()=>{const text=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');const values={};let removed=false,scrolled=false,pinChecked=false;const c={window:{__savedDeliveryAddress:{parts,...body}},document:{getElementById:id=>values[id]||(values[id]={remove(){removed=true},scrollIntoView(){scrolled=true}})},syncCheckoutAddress(){},validateCheckoutMobile(){},addressPinChanged(){pinChecked=true},toast(){}};vm.createContext(c);vm.runInContext(text.split('\n').find(x=>x.startsWith('function useSavedDeliveryAddress()')),c);c.useSavedDeliveryAddress();assert.equal(values.checkoutHouse.value,parts.house);assert.equal(values.checkoutVillage.value,'Main Road, Central Area');assert.equal(values.checkoutLandmark.value,'Near Park');assert.equal(values.fullName.value,body.name);assert.equal(values.mobile.value,body.phone);assert.equal(values.pin.value,body.pincode);assert.equal(values.city.value,body.city);assert.equal(values.state.value,body.state);assert.equal(removed,true);assert.equal(scrolled,true);assert.equal(pinChecked,true)});
test('different address clears checkout and verification without changing saved address',()=>{const text=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');const nodes={};let removed=false,focused=false;const saved={...body,parts};const c={window:{__savedDeliveryAddress:saved,__checkoutPinVerified:'110001',__deliveryUnavailable:false},document:{getElementById:id=>nodes[id]||(nodes[id]={value:'old',classList:{remove(){}},removeAttribute(){},remove(){removed=true},scrollIntoView(){},focus(){focused=true}})},validateCheckoutMobile(){}};vm.createContext(c);for(const name of ['useDifferentDeliveryAddress','syncCheckoutAddress','addressPinChanged']){if(name==='addressPinChanged'){vm.runInContext(text.slice(text.indexOf('function addressPinChanged(){'),text.indexOf('\nfunction cat(')),c)}else vm.runInContext(text.split('\n').find(x=>x.startsWith('function '+name+'(')),c)}c.useDifferentDeliveryAddress();for(const id of ['fullName','mobile','pin','city','state','checkoutHouse','checkoutVillage','checkoutLandmark','address'])assert.equal(nodes[id].value,'');assert.equal(c.window.__checkoutPinVerified,'');assert.equal(c.window.__deliveryUnavailable,true);assert.equal(c.window.__savedDeliveryAddress,saved);assert.equal(removed,true);assert.equal(focused,true)});
