import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import vm from 'node:vm';
import {installCartSchema,cartState,applyCartMutation} from '../scripts/cart-state.js';
function database(){const raw=new DatabaseSync(':memory:');let tx=0;const db={exec:s=>raw.exec(s),prepare:s=>raw.prepare(s),transaction:fn=>(...args)=>{const name='t'+(++tx);raw.exec('SAVEPOINT '+name);try{const result=fn(...args);raw.exec('RELEASE '+name);return result}catch(e){raw.exec('ROLLBACK TO '+name);raw.exec('RELEASE '+name);throw e}}};db.exec(`PRAGMA foreign_keys=ON;CREATE TABLE users(id INTEGER PRIMARY KEY);CREATE TABLE products(id INTEGER PRIMARY KEY,size_options TEXT,color TEXT,stock INTEGER,name TEXT);INSERT INTO users VALUES(1),(2);INSERT INTO products VALUES(1,'S,M','Blue',10,'Dress'),(2,'M','Red',10,'Set'),(3,'M','Blue',10,'Shirt');CREATE TABLE cart_items(user_id INTEGER,product_id INTEGER,size TEXT,quantity INTEGER CHECK(quantity BETWEEN 1 AND 20),updated_at TEXT DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(user_id,product_id,size),FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(product_id) REFERENCES products(id));CREATE TABLE orders(id INTEGER PRIMARY KEY,user_id INTEGER,cart_cleanup_json TEXT DEFAULT '',cart_cleanup_done INTEGER DEFAULT 0);`);installCartSchema(db);return db}
let seq=0;function op(changes=[],wishes=[],userId=1){return {userId,operationId:'operation_'+String(++seq).padStart(12,'0'),changes,wishes}}
const change=(id,before,after,size='M')=>({id,size,before,after});
test('two devices preserve unrelated additions',()=>{const d=database();applyCartMutation(d,1,op([change(1,0,1)]));applyCartMutation(d,1,op([change(2,0,1)]));assert.equal(cartState(d,1).items.length,2)});
test('same-item stale edit rejected without losing newer value',()=>{const d=database();applyCartMutation(d,1,op([change(1,0,2)]));assert.throws(()=>applyCartMutation(d,1,op([change(1,0,1)])),e=>e.status===409);assert.equal(cartState(d,1).items[0].quantity,2)});
test('network retry applies once, even after another device edit',()=>{const d=database(),a=op([change(1,0,1)]);applyCartMutation(d,1,a);applyCartMutation(d,1,op([change(1,1,2)]));applyCartMutation(d,1,a);assert.equal(cartState(d,1).items[0].quantity,2)});
test('wrong account rejected; other user records unchanged',()=>{const d=database();assert.throws(()=>applyCartMutation(d,2,op([change(1,0,1)])),e=>e.status===409);assert.equal(cartState(d,2).items.length,0)});
test('invalid size/quantity rejected atomically',()=>{const d=database();for(const c of [change(1,0,21),change(1,0,1,'XX')])assert.throws(()=>applyCartMutation(d,1,op([change(2,0,1),c])));assert.equal(cartState(d,1).items.length,0)});
const source=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');const block=source.slice(source.indexOf('let shoppingOwner='),source.indexOf('function wishlistStorageKey'));
function storage(){const m=new Map();return {get length(){return m.size},key:i=>[...m.keys()][i],getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)}}
function client(d){const localStorage=storage();let online=true;const c={user:{id:1,role:'customer'},cart:[],wishlist:[],cartSaveQueue:Promise.resolve(),localStorage,crypto:{randomUUID:()=>('id_'+(++seq)).padEnd(24,'x')},esc:x=>x,document:{getElementById:()=>null,createElement:()=>({style:{}}),body:{appendChild(){}}},window:{addEventListener(){}},updateCartCount(){},auth(){},clearCheckoutState(){},closeM(){},restoreSession(){},api:async(url,opts={})=>{if(!online)throw Error('offline');return url==='/api/cart'?cartState(d,c.user.id):applyCartMutation(d,c.user.id,opts.body)}};vm.createContext(c);vm.runInContext(block,c);return {c,offline:()=>online=false,online:()=>online=true,run:s=>vm.runInContext(s,c)}}
test('client blocks mutations until load complete',async()=>{const {c}=client(database());assert.equal(c.canChangeShopping(),false);await c.loadCartForCurrentUser();assert.equal(c.canChangeShopping(),true)});
test('offline operation survives reload and retries once',async()=>{const d=database(),x=client(d);await x.c.loadCartForCurrentUser();x.offline();assert.equal(await x.c.commitShopping([{id:1,size:'M',quantity:1}],[]),false);assert.ok(x.c.pendingShopping());x.online();await x.c.loadCartForCurrentUser();assert.ok(x.c.pendingShopping());assert.equal(await x.c.retryShopping(),true);assert.equal(x.c.pendingShopping(),null);assert.equal(cartState(d,1).items.length,1)});
test('delayed account-A load cannot populate account B',async()=>{const x=client(database());let reply;x.c.api=()=>new Promise(r=>reply=r);const loading=x.c.loadCartForCurrentUser();x.c.user={id:2};reply({userId:1,items:[{id:1,size:'M',quantity:1}],wishlist:[]});await loading;assert.equal(x.c.cart.length,0);assert.equal(x.c.canChangeShopping(),false)});
test('concurrent response cannot remove locally pending draft',async()=>{const d=database(),x=client(d);await x.c.loadCartForCurrentUser();applyCartMutation(d,1,op([change(1,0,2)]));assert.equal(await x.c.commitShopping([{id:1,size:'M',quantity:1}],[]),false);assert.ok(x.c.pendingShopping());assert.equal(cartState(d,1).items[0].quantity,2)});

test('checkout removes purchased row but keeps other-device additions',async()=>{const d=database(),x=client(d);applyCartMutation(d,1,op([change(1,0,1)]));await x.c.loadCartForCurrentUser();applyCartMutation(d,1,op([change(2,0,1)]));await x.c.removePurchasedCart([{id:1,size:'M',quantity:1}],1,123);assert.deepEqual(cartState(d,1).items.map(i=>i.id),[2]);applyCartMutation(d,1,op([change(1,0,1)]));await x.c.removePurchasedCart([{id:1,size:'M',quantity:1}],1,123);assert.equal(cartState(d,1).items.length,2)});
test('checkout cleanup preserves concurrent quantity edit',async()=>{const d=database(),x=client(d);applyCartMutation(d,1,op([change(1,0,2)]));await x.c.loadCartForCurrentUser();await x.c.removePurchasedCart([{id:1,size:'M',quantity:1}],1,124);assert.equal(cartState(d,1).items[0].quantity,2);assert.ok(x.c.pendingShopping())});
test('lost acknowledgement retries without duplicating addition',async()=>{const d=database(),x=client(d);await x.c.loadCartForCurrentUser();const api=x.c.api;let lose=true;x.c.api=async(...args)=>{const result=await api(...args);if(lose){lose=false;throw Error('response lost')}return result};assert.equal(await x.c.commitShopping([{id:1,size:'M',quantity:1}]),false);assert.equal(await x.c.retryShopping(),true);assert.equal(cartState(d,1).items[0].quantity,1)});
test('cart row limit rolls back addition and receipt',()=>{const d=database();for(let id=4;id<=51;id++)d.prepare("INSERT INTO products VALUES(?,'M','Blue',10,'Dress')").run(id);applyCartMutation(d,1,op(Array.from({length:50},(_,i)=>change(i+1,0,1))));const a=op([change(51,0,1)]);assert.throws(()=>applyCartMutation(d,1,a),e=>e.status===400);assert.equal(cartState(d,1).items.length,50);assert.equal(d.prepare('SELECT count(*) n FROM cart_mutations WHERE operation_id=?').get(a.operationId).n,0)});
test('failed initial load prevents destructive empty-cart write',async()=>{const x=client(database());x.offline();await x.c.loadCartForCurrentUser();assert.equal(await x.c.commitShopping([]),false)});
test('null change returns validation error',()=>{assert.throws(()=>applyCartMutation(database(),1,op([null])),e=>e.status===400)});
