import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {requestOrderPickup,validatePickupDate} from '../scripts/courier-pickup.js';
function fixture(){const db=new DatabaseSync(':memory:');db.exec("CREATE TABLE orders(id INTEGER,pickup_state TEXT DEFAULT '',pickup_requested_date TEXT,pickup_confirmed_date TEXT,pickup_token TEXT,shiprocket_status TEXT,updated_at TEXT); INSERT INTO orders(id) VALUES(1)");return db}
const order={id:1,shiprocket_shipment_id:'55'},date='2099-01-01';
test('India date boundary and invalid calendar dates',()=>{assert.equal(validatePickupDate('2026-09-07',new Date('2026-09-06T20:00:00Z')),'2026-09-07');for(const d of ['2026-09-06','2026-02-30','garbage',''])assert.throws(()=>validatePickupDate(d,new Date('2026-09-06T20:00:00Z')))});
test('confirmed response persists carrier date and token; replay does not book again',async()=>{const db=fixture();let calls=0;const request=async(path,{body})=>{calls++;assert.deepEqual(body,{shipment_id:[55],pickup_date:[date]});return{pickup_status:1,response:{pickup_scheduled_date:'2099-01-02',pickup_token_number:'P123'}}};await requestOrderPickup(db,request,order,date);const saved=db.prepare('SELECT * FROM orders').get();assert.equal(saved.pickup_state,'CONFIRMED');assert.equal(saved.pickup_confirmed_date,'2099-01-02');assert.equal(saved.pickup_token,'P123');await requestOrderPickup(db,request,saved,date);assert.equal(calls,1)});
test('explicit rejection allows retry and never marks scheduled',async()=>{const db=fixture();await assert.rejects(requestOrderPickup(db,async()=>({pickup_status:0}),order,date));assert.equal(db.prepare('SELECT * FROM orders').get().pickup_state,'FAILED');await requestOrderPickup(db,async()=>({pickup_status:1}),order,date);assert.equal(db.prepare('SELECT * FROM orders').get().pickup_state,'CONFIRMED')});
test('timeout and malformed response remain unknown and prevent duplicate request',async()=>{for(const request of [async()=>{throw Error('timeout')},async()=>({})]){const db=fixture();await assert.rejects(requestOrderPickup(db,request,order,date));const saved=db.prepare('SELECT * FROM orders').get();assert.equal(saved.pickup_state,'UNKNOWN');await assert.rejects(requestOrderPickup(db,()=>assert.fail('duplicate'),saved,date))}});
test('concurrent stale requests are stopped by persisted claim',async()=>{const db=fixture();let done;const first=requestOrderPickup(db,()=>new Promise(r=>done=r),order,date);await assert.rejects(requestOrderPickup(db,()=>assert.fail('duplicate'),order,date));done({pickup_status:1});await first});
test('legacy scheduled shipment never gets a duplicate pickup',async()=>{await requestOrderPickup(fixture(),()=>assert.fail('duplicate'),{...order,shiprocket_status:'PICKUP_SCHEDULED'},date)});
