import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const source=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');
const data={order:{id:13,created_at:'2026-09-07',delivery_name:'Buyer <script>',delivery_address_line:'House 42',delivery_city:'Guwahati',delivery_state:'Assam',delivery_pincode:'781028',payment_method:'COD',payment_status:'PENDING',total:1999},items:[{name:'Dress',size:'M',color:'Blue',quantity:2},{name:'Top',size:'L',quantity:1}],reviewKey:'review123'};
function context(extra={}){const c={...extra};vm.createContext(c);for(const name of ['esc','courierReviewDetails'])vm.runInContext(source.split('\n').find(x=>x.startsWith('function '+name+'(')),c);return c}
test('review contains exact order, address, products and total quantity with safe escaping',()=>{const c=context({orderTimeText:x=>x});const html=c.courierReviewDetails(data);for(const text of ['Order #13','Total quantity: 3','House 42','Dress','Top','COD','2026-09-07'])assert(html.includes(text));assert(!html.includes('Buyer <script>'))});
function flow(extra={}){const c=context({Set,...extra});vm.runInContext('const courierReviewLocks=new Set();\n'+source.split('\n').find(x=>x.startsWith('async function reviewAndBookCourier(')),c);return c}
test('cancel review never books courier',async()=>{let calls=0;const c=flow({api:async()=>{calls++;return data},showCourierBookingReview:async()=>false});await c.reviewAndBookCourier(13);assert.equal(calls,1)});
test('confirm sends reviewed order token and edited pickup date',async()=>{let body;const c=flow({api:async(url,opt)=>{if(opt)body=opt.body;return data},showCourierBookingReview:async()=> '2099-01-04',toast:()=>{},adminStat:async()=>{}});await c.reviewAndBookCourier(13);assert.deepEqual(JSON.parse(JSON.stringify(body)),{status:'PACKED',pickup_date:'2099-01-04',review_key:'review123'})});
test('double click opens one review and sends one booking',async()=>{let resolve,reads=0,writes=0;const c=flow({api:async(u,o)=>{o?writes++:reads++;return data},showCourierBookingReview:()=>new Promise(r=>resolve=r),toast:()=>{},adminStat:async()=>{}});const first=c.reviewAndBookCourier(13);await Promise.resolve();await c.reviewAndBookCourier(13);resolve('2099-01-04');await first;assert.equal(reads,1);assert.equal(writes,1)});
test('failed preview does not open or book and permits a later retry',async()=>{let errors=0;const c=flow({api:async()=>{throw Error('refresh')},alert:()=>errors++,showCourierBookingReview:()=>{throw Error('must not open')}});await c.reviewAndBookCourier(13);await c.reviewAndBookCourier(13);assert.equal(errors,2)});
