import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const source=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8'),c={};vm.createContext(c);
for(const name of ['esc','printStoreAddress','maskedPrintPhone','privatePrintAddress','printItemRows','printGstBill','orderDate','orderTimeText','packingCourierDetails'])vm.runInContext(source.split('\n').find(x=>x.startsWith('function '+name+'(')),c);
test('mask handles local and country-prefixed phone',()=>{assert.equal(c.maskedPrintPhone('+91 98765 43210'),'******3210');assert.equal(c.maskedPrintPhone('9876543210'),'******3210');assert.equal(c.maskedPrintPhone(''),'—')});
test('address strips repeated and formatted phone but preserves house and PIN',()=>{for(const phone of ['9876543210','+91 98765-43210','91 98765 43210']){const cleaned=c.privatePrintAddress('Customer, '+phone+', House 42, Guwahati 781028, Mobile: '+phone,'9876543210');assert(!cleaned.includes('98765'));assert(cleaned.includes('House 42'));assert(cleaned.includes('781028'));assert(!cleaned.includes('Mobile:'))}});
test('combined print hides slip mobile and masks legacy bill without modifying order',async()=>{const order={id:8,address:'Customer, 9876543210, House 42, Guwahati 781028',customer_name:'Customer',customer_phone:'9876543210',total:1000,payment_method:'COD',payment_status:'PENDING',created_at:'2026-09-06',status:'CONFIRMED'};const before=JSON.stringify(order);let html;c.prepareAdminPrintWindow=()=>({close(){}});c.api=async()=>({order,items:[],store:{address:'Seller address'}});c.openAdminPrint=(title,body)=>html=body;c.alert=m=>{throw Error(m)};vm.runInContext(source.slice(source.indexOf('async function printOrderDocument('),source.indexOf('async function printReturnDocument(')),c);await c.printOrderDocument(8);assert(!html.includes('9876543210'));const packing=html.split('<div class="packing-section">')[1].split('<hr class="cut-divider">')[0];assert(!packing.includes('Mobile:'));assert(html.includes('******3210'));assert(html.includes('Seller address'));assert.equal(JSON.stringify(order),before)});
test('GST delivery address removes the repeated customer number shown in screenshot',()=>{const phone='6003820392',address='D j Deori, 6003820392, 3 No Murkong Selek, Jandli, Post office, Jonai, Assam, 787060';const g={seller:{legal_name:'Ashwini',gstin:'TEST',address:'Seller Street',city:'Guwahati'},buyer:{name:'D j Deori',phone,address},lines:[],intra_state:true,issued_at:'2026-09-06',invoice_number:'TEST-12',place_of_supply:'Assam',total_paise:119900,taxable_paise:114190,discount_paise:0};const html=c.printGstBill(g,{id:12,payment_method:'COD',payment_status:'PENDING'});assert(!html.includes(phone));assert(html.includes('******0392'));assert(html.includes('3 No Murkong Selek'));assert(html.includes('787060'));assert.equal(g.buyer.address,address)});
test('booked courier appears with AWB, shipment and IST dispatch time',()=>{const html=c.packingCourierDetails({courier_name:'Delhivery',tracking_number:'AWB12345',shiprocket_shipment_id:'555',shiprocket_status:'PICKUP_SCHEDULED',dispatched_at:'2026-09-06 10:00:00',customer_phone:'9876543210'});assert(html.includes('Delhivery'));assert(html.includes('AWB12345'));assert(html.includes('555'));assert(html.includes('03:30:00 pm IST'));assert(!html.includes('9876543210'))});
test('manual and pending booking details are handled without fabricated AWB',()=>{assert(c.packingCourierDetails({courier_name:'India Post',tracking_number:'IN123'}).includes('IN123'));assert(c.packingCourierDetails({shiprocket_awb:'SR456'}).includes('SR456'));assert(c.packingCourierDetails({}).includes('Pending — not assigned yet'));assert(c.packingCourierDetails({courier_name:'<script>'}).includes('&lt;script&gt;'))});

test('packing distinguishes requested and carrier confirmed pickup without exposing phone',()=>{const html=c.packingCourierDetails({pickup_requested_date:'2099-01-01',pickup_confirmed_date:'2099-01-02',pickup_state:'CONFIRMED',pickup_token:'P123',customer_phone:'9876543210'});assert(html.includes('Requested pickup: 2099-01-01'));assert(html.includes('Courier scheduled pickup: 2099-01-02'));assert(html.includes('P123'));assert(!html.includes('9876543210'));assert(!html.includes('Dispatched:'))});
