import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {createReturnRefundService} from '../scripts/return-refund.js';
const entity=(status='pending')=>({id:'rfnd_1',payment_id:'pay_1',amount:119900,currency:'INR',receipt:'ASH-RET-REF-1',status});
function fixture(provider={refund:async()=>entity()}){const db=new DatabaseSync(':memory:');db.transaction=fn=>(...args)=>{db.exec('SAVEPOINT fixture');try{const result=fn(...args);db.exec('RELEASE fixture');return result}catch(e){db.exec('ROLLBACK TO fixture; RELEASE fixture');throw e}};db.exec(`CREATE TABLE returns(id INTEGER PRIMARY KEY,order_id INTEGER,user_id INTEGER,request_type TEXT,status TEXT,updated_at TEXT);INSERT INTO returns VALUES(1,1,1,'RETURN_REFUND','INSPECTION_PASSED','');CREATE TABLE orders(id INTEGER PRIMARY KEY,status TEXT,payment_status TEXT,payment_method TEXT,razorpay_payment_id TEXT,total REAL,refund_status TEXT DEFAULT '',refund_amount REAL DEFAULT 0,razorpay_refund_id TEXT,refund_requested_at TEXT,updated_at TEXT);INSERT INTO orders(id,status,payment_status,payment_method,razorpay_payment_id,total) VALUES(1,'DELIVERED','PAID','RAZORPAY','pay_1',1199);CREATE TABLE razorpay_refunds(refund_id TEXT PRIMARY KEY,order_id INTEGER,payment_id TEXT,amount_paise INTEGER,status TEXT,updated_at TEXT);CREATE TABLE events(title TEXT);`);const svc=createReturnRefundService({db,provider,addEvent:(id,user,status,title)=>db.prepare('INSERT INTO events VALUES(?)').run(title)});return {db,svc,order:()=>db.prepare('SELECT * FROM orders').get(),ret:()=>db.prepare('SELECT * FROM returns').get()}}
test('refund waits for provider processing and completes once confirmed',async()=>{const f=fixture();await f.svc.start(1,9);assert.equal(f.ret().status,'INSPECTION_PASSED');assert.equal(f.order().payment_status,'REFUND_PENDING');f.svc.apply(entity('processed'));assert.equal(f.ret().status,'COMPLETED');assert.equal(f.order().payment_status,'REFUNDED');assert.equal(f.order().refund_amount,1199);f.svc.apply(entity('pending'));assert.equal(f.order().payment_status,'REFUNDED');assert.equal(f.db.prepare('SELECT count(*) n FROM events').get().n,2)});
test('concurrent clicks and later retries send one payout request',async()=>{let resolve,calls=0;const f=fixture({refund:()=>{calls++;return new Promise(r=>resolve=r)}});const first=f.svc.start(1,9);await f.svc.start(1,9);resolve(entity());await first;await f.svc.start(1,9);assert.equal(calls,1)});
test('timeout persists across service recreation and sync finds receipt without new payout',async()=>{let calls=0;const f=fixture({refund:async()=>{calls++;throw Error('timeout')}});await assert.rejects(f.svc.start(1,9));assert.equal(f.svc.job(1).state,'UNKNOWN');const restarted=createReturnRefundService({db:f.db,provider:{refund:()=>{calls++},fetchMultipleRefund:async()=>({items:[entity('processed')]})}});await restarted.start(1,9);await restarted.sync(1);assert.equal(calls,1);assert.equal(f.ret().status,'COMPLETED')});
test('inspection, delivered payment and return type gate refunds',async()=>{for(const sql of ["UPDATE returns SET status='RECEIVED'","UPDATE returns SET request_type='EXCHANGE'","UPDATE orders SET status='SHIPPED'","UPDATE orders SET payment_status='PENDING'","UPDATE orders SET refund_status='PENDING'"]){const f=fixture();f.db.exec(sql);await assert.rejects(f.svc.start(1,9));assert.equal(f.svc.job(1),undefined)}});
test('wrong provider payment, amount and currency cannot complete return',async()=>{for(const change of [{payment_id:'pay_other'},{amount:1},{currency:'USD'}]){const f=fixture();await f.svc.start(1,9);assert.throws(()=>f.svc.apply({...entity('processed'),...change}));assert.equal(f.ret().status,'INSPECTION_PASSED')}});
test('failed refund stays open and cannot be retried as a new payout',async()=>{let calls=0;const f=fixture({refund:async()=>{calls++;return entity('failed')}});await f.svc.start(1,9);await f.svc.start(1,9);assert.equal(calls,1);assert.equal(f.ret().status,'INSPECTION_PASSED');assert.equal(f.order().payment_status,'REFUND_FAILED')});
test('webhook before API response cannot be regressed by pending response',async()=>{const f=fixture({refund:async()=>{f.svc.apply(entity('processed'));return entity()}});await f.svc.start(1,9);assert.equal(f.ret().status,'COMPLETED');assert.equal(f.svc.job(1).state,'PROCESSED')});
test('COD requires recorded external transfer and rejects online refund',async()=>{const f=fixture();f.db.exec("UPDATE orders SET payment_method='COD'");await assert.rejects(f.svc.start(1,9));assert.throws(()=>f.svc.manual(1,9,''));f.svc.manual(1,9,'UTR-123456');f.svc.manual(1,9,'UTR-123456');assert.equal(f.order().refund_status,'MANUAL_RECORDED');assert.equal(f.ret().status,'COMPLETED');assert.equal(f.db.prepare('SELECT count(*) n FROM events').get().n,1)});
test('online refunds cannot be manually marked paid',()=>{const f=fixture();assert.throws(()=>f.svc.manual(1,9,'UTR-123456'));assert.equal(f.ret().status,'INSPECTION_PASSED')});
test('customer view omits payout references and operator identity',async()=>{const f=fixture();await f.svc.start(1,9);const v=f.svc.view(f.ret());assert.equal(v.return_refund_state,'PENDING');assert(!('return_refund_reference'in v));assert(!('actor_id'in v));assert.equal(f.svc.view(f.ret(),true).return_refund_reference,'rfnd_1')});
test('unmatched sync remains blocked without creating another payment',async()=>{const f=fixture({refund:async()=>{throw Error('lost')},fetchMultipleRefund:async()=>({items:[]})});await assert.rejects(f.svc.start(1,9));await assert.rejects(f.svc.sync(1));assert.equal(f.svc.job(1).state,'UNKNOWN')});
test('database event failure rolls back refund completion for retry',async()=>{const f=fixture();await f.svc.start(1,9);const broken=createReturnRefundService({db:f.db,provider:{},addEvent:()=>{throw Error('disk')}});assert.throws(()=>broken.apply(entity('processed')));assert.equal(f.ret().status,'INSPECTION_PASSED');f.svc.apply(entity('processed'));assert.equal(f.ret().status,'COMPLETED')});

import fs from 'node:fs';import vm from 'node:vm';
function ui(){const source=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8'),c={};vm.createContext(c);for(const name of ['esc','returnRefundButtons','customerRefundStatus'])vm.runInContext(source.split('\n').find(x=>x.startsWith('function '+name+'(')),c);return c}
test('admin refund controls follow inspection and pending state',()=>{const c=ui(),r={id:1,request_type:'RETURN_REFUND',status:'RECEIVED',total:1199,payment_method:'RAZORPAY'};assert(!c.returnRefundButtons(r).includes('Refund to Original Payment'));r.status='INSPECTION_PASSED';assert(c.returnRefundButtons(r).includes('Refund to Original Payment'));r.return_refund_state='PENDING';assert(c.returnRefundButtons(r).includes('Sync Refund'));assert(!c.returnRefundButtons(r).includes('Refund to Original Payment'))});
test('refund reference is escaped and customer text distinguishes manual record',()=>{const c=ui();assert(!c.returnRefundButtons({request_type:'RETURN_REFUND',return_refund_reference:'<img onerror=attack()>',return_refund_state:'PROCESSED'}).includes('<img'));assert(c.customerRefundStatus({return_refund_state:'MANUAL_RECORDED',return_refund_amount_paise:10000}).includes('recorded by Ashwini'))});
test('declining refund confirmation never calls payment endpoint',async()=>{const source=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8'),c={confirmAdminOrderOnPage:async()=>false,api:()=>{throw Error('must not call')},alert:()=>{throw Error('unexpected')}};vm.createContext(c);vm.runInContext(source.split('\n').find(x=>x.startsWith('async function processReturnRefund(')),c);await c.processReturnRefund(1,'start',1199)});
