import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {installReturnCourierSchema,returnPayload,createReturnCourierService,applyReturnWebhook,returnTarget,secureLabel} from '../scripts/return-courier.js';
function fixture(){const db=new DatabaseSync(':memory:');db.exec("CREATE TABLE returns(id INTEGER PRIMARY KEY,order_id INTEGER,user_id INTEGER,status TEXT,pickup_at TEXT DEFAULT '',updated_at TEXT);INSERT INTO returns(id,order_id,user_id,status) VALUES(1,40,2,'APPROVED'),(2,41,3,'APPROVED');CREATE TABLE events(id INTEGER,status TEXT)");installReturnCourierSchema(db);const addEvent=(id,u,status)=>db.prepare('INSERT INTO events VALUES(?,?)').run(id,status);return {db,addEvent,read:()=>db.prepare('SELECT * FROM returns WHERE id=1').get()}}
const order={status:'DELIVERED',delivery_name:'Buyer',delivery_address_line:'House 42',delivery_city:'Delhi',delivery_state:'Delhi',delivery_pincode:'110001',customer_phone:'9876543210',customer_email:'buyer@example.com'},items=[{product_id:1,size:'M',quantity:2,unit_price:100,name:'Dress'}],dest={name:'Ashwini',address:'Warehouse',city:'Guwahati',state:'Assam',pin:'781028',phone:'9876543211',email:'shop@example.com'};
const body=()=>returnPayload({id:1},order,items,dest);const response={status:1,payload:{order_created:1,order_id:100,shipment_id:200,awb_code:'RET123',courier_name:'Reverse Courier',pickup_generated:1,pickup_scheduled_date:'2099-01-02 09:00:00'}};
test('reverse payload has customer pickup, warehouse destination and no COD collection',()=>{const p=body();assert.equal(p.pickup_address,'House 42');assert.equal(p.shipping_address,'Warehouse');assert.equal(p.payment_method,'PREPAID');assert.equal(p.request_pickup,true);assert.equal(p.order_id,'ASH-RET-1');assert.equal(p.weight,1);assert.equal(p.height,10);assert.equal(p.sub_total,200)});
test('incomplete addresses and undelivered orders fail before any provider request',()=>{for(const o of [{...order,status:'SHIPPED'},{...order,delivery_pincode:''},{...order,customer_phone:''}])assert.throws(()=>returnPayload({id:1},o,items,dest));assert.throws(()=>returnPayload({id:1},order,items,{...dest,address:''}));assert.throws(()=>returnPayload({id:1},order,[],dest))});
test('successful booking persists separate return identifiers and confirms pickup only',async()=>{const f=fixture(),svc=createReturnCourierService({...f,request:async(url)=>{assert.equal(url,'/shipments/create/return-shipment');return response}});await svc.book(1,body());assert.equal(f.read().status,'PICKUP_SCHEDULED');assert.equal(f.read().sr_awb,'RET123');assert.equal(f.read().pickup_at,response.payload.pickup_scheduled_date);assert.equal(f.db.prepare('SELECT status FROM returns WHERE id=2').get().status,'APPROVED');await assert.rejects(svc.book(1,body()));assert.equal(f.db.prepare('SELECT count(*) AS n FROM events').get().n,1)});
test('concurrent booking claim prevents duplicate external requests',async()=>{const f=fixture();let resolve,calls=0;const svc=createReturnCourierService({...f,request:()=>{calls++;return new Promise(r=>resolve=r)}});const first=svc.book(1,body());await assert.rejects(svc.book(1,body()));resolve(response);await first;assert.equal(calls,1)});
test('unknown or partial response retains state and blocks unsafe retries',async()=>{for(const request of [async()=>{throw Error('timeout')},async()=>({status:0,payload:{order_id:100,shipment_id:200}}),async()=>({})]){const f=fixture(),svc=createReturnCourierService({...f,request});await assert.rejects(svc.book(1,body()));assert.equal(f.read().status,'APPROVED');assert(['UNKNOWN','REVIEW'].includes(f.read().sr_booking_state));await assert.rejects(svc.book(1,body()))}});
test('label failure does not lose confirmed booking and label retry is separate',async()=>{const f=fixture();let labels=0;const svc=createReturnCourierService({...f,request:async(url)=>{if(url.includes('return-shipment'))return response;labels++;return labels===1?{}:{label_url:'https://example.com/label.pdf'}}});await svc.book(1,body());await assert.rejects(svc.label(1));assert.equal(f.read().status,'PICKUP_SCHEDULED');assert.equal(await svc.label(1),'https://example.com/label.pdf');await svc.label(1);assert.equal(labels,2);assert.equal(secureLabel('javascript:alert(1)'), '')});
test('return webhook ignores empty IDs and forward shipments',()=>{const f=fixture();assert.equal(applyReturnWebhook(f.db,{awb:'FORWARD'},'a',f.addEvent),false);assert.equal(applyReturnWebhook(f.db,{},'b',f.addEvent),false)});
test('reverse delivery means received, never refund/replacement complete; stale events cannot regress',async()=>{const f=fixture();await createReturnCourierService({...f,request:async()=>response}).book(1,body());for(const [i,s] of ['PICKED UP','IN TRANSIT','DELIVERED','PICKUP SCHEDULED'].entries())assert(applyReturnWebhook(f.db,{awb:'RET123',current_status:s},String(i),f.addEvent));assert.equal(f.read().status,'RECEIVED');const n=f.db.prepare('SELECT count(*) AS n FROM events').get().n;applyReturnWebhook(f.db,{awb:'RET123',current_status:'DELIVERED'},'2',f.addEvent);assert.equal(f.db.prepare('SELECT count(*) AS n FROM events').get().n,n);assert.equal(returnTarget('DELIVERED','INSPECTION_PASSED'),'INSPECTION_PASSED')});
test('conflicting IDs are rejected and failed event processing can retry',async()=>{const f=fixture();await createReturnCourierService({...f,request:async()=>response}).book(1,body());assert.throws(()=>applyReturnWebhook(f.db,{awb:'RET123',shipment_id:'999',current_status:'DELIVERED'},'bad',f.addEvent));assert.throws(()=>applyReturnWebhook(f.db,{awb:'RET123',current_status:'DELIVERED'},'retry',()=>{throw Error('db failed')}));assert.equal(f.read().status,'PICKUP_SCHEDULED');applyReturnWebhook(f.db,{awb:'RET123',current_status:'DELIVERED'},'retry',f.addEvent);assert.equal(f.read().status,'RECEIVED')});
test('courier cancellation closes only pre-pickup returns',()=>{assert.equal(returnTarget('RETURN CANCELED','APPROVED'),'CANCELLED');assert.equal(returnTarget('CANCELED','IN_TRANSIT'),'IN_TRANSIT')});
