import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import vm from 'node:vm';
import {installWishlistSchema,wishlistState,mutateWishlist} from '../scripts/wishlist-state.js';
function database(){const raw=new DatabaseSync(':memory:');const db={exec:s=>raw.exec(s),prepare:s=>raw.prepare(s),transaction:fn=>(...args)=>{raw.exec('BEGIN');try{const v=fn(...args);raw.exec('COMMIT');return v}catch(e){raw.exec('ROLLBACK');throw e}}};db.exec('PRAGMA foreign_keys=ON;CREATE TABLE users(id INTEGER PRIMARY KEY);INSERT INTO users VALUES(1),(2);CREATE TABLE products(id INTEGER PRIMARY KEY);INSERT INTO products VALUES(1),(2),(3);');installWishlistSchema(db);return db}
let seq=0;const operation=(id,saved=true,userId=1)=>({userId,operationId:('wish_test_'+(++seq)).padEnd(20,'_'),changes:[{id,saved}]});
const source=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');const block=source.slice(source.indexOf('function wishlistStorageKey'),source.indexOf('function ensureAdminNotificationBadgeStyle'));
function storage(){const m=new Map();return {get length(){return m.size},key:i=>[...m.keys()][i],getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)}}
function client(d,localStorage=storage()){let online=true;const c={user:{id:1},wishlist:[],localStorage,crypto:{randomUUID:()=>('id_'+(++seq)).padEnd(24,'x')},esc:x=>x,document:{getElementById:()=>null,createElement:()=>({style:{}}),body:{appendChild(){}}},window:{addEventListener(){}},auth(){},api:async(url,opts)=>{if(!online)throw Error('offline');return url==='/api/wishlist'?wishlistState(d,c.user.id):mutateWishlist(d,c.user.id,opts.body)}};vm.createContext(c);vm.runInContext(block,c);return {c,offline:()=>online=false,online:()=>online=true}}
test('different devices preserve unrelated additions and removals',()=>{const d=database();mutateWishlist(d,1,operation(1));mutateWishlist(d,1,operation(2));mutateWishlist(d,1,operation(1,false));assert.deepEqual(wishlistState(d,1).items,[2])});
test('lost-response retry does not undo a later removal',()=>{const d=database(),op=operation(1);mutateWishlist(d,1,op);mutateWishlist(d,1,operation(1,false));mutateWishlist(d,1,op);assert.deepEqual(wishlistState(d,1).items,[])});
test('wrong shared-cookie account cannot mutate wishlist',()=>{const d=database();assert.throws(()=>mutateWishlist(d,2,operation(1)),e=>e.status===409);assert.deepEqual(wishlistState(d,2).items,[])});
test('invalid batch rolls back earlier entries',()=>{const d=database(),op=operation(1);op.changes.push({id:999,saved:true});assert.throws(()=>mutateWishlist(d,1,op));assert.deepEqual(wishlistState(d,1).items,[])});
test('legacy import ignores deleted products and merges',async()=>{const d=database(),x=client(d);mutateWishlist(d,1,operation(2));x.c.localStorage.setItem('ashwiniWishlist_1','[1,999]');assert.equal(await x.c.loadWishlistForCurrentUser(),true);assert.deepEqual(wishlistState(d,1).items,[1,2]);mutateWishlist(d,1,operation(1,false));await x.c.loadWishlistForCurrentUser();assert.deepEqual(wishlistState(d,1).items,[2])});
test('same account on another browser sees saved wishlist',async()=>{const d=database(),a=client(d),b=client(d);assert.equal(await a.c.setWishlistItem(1,true),true);await b.c.loadWishlistForCurrentUser();assert.equal(JSON.stringify(b.c.wishlist),'[1]');assert.equal(await b.c.setWishlistItem(2,true),true);await a.c.loadWishlistForCurrentUser();assert.equal(JSON.stringify(a.c.wishlist),'[1,2]')});
test('pending write survives page reload and retries',async()=>{const d=database(),x=client(d);await x.c.loadWishlistForCurrentUser();x.c.queueWishlist(1,[{id:1,saved:true}]);x.offline();assert.equal(await x.c.loadWishlistForCurrentUser(),false);const y=client(d,x.c.localStorage);assert.equal(await y.c.loadWishlistForCurrentUser(),true);assert.deepEqual(wishlistState(d,1).items,[1]);assert.equal(y.c.pendingWishlist(1),null)});
test('late response cannot show another account wishlist',async()=>{const x=client(database());let reply;x.c.api=()=>new Promise(r=>reply=r);const task=x.c.loadWishlistForCurrentUser();x.c.user={id:2};reply({userId:1,items:[1]});assert.equal(await task,false);assert.equal(x.c.wishlist.length,0)});
test('legacy acknowledgement loss retries once without reimport',async()=>{const d=database(),x=client(d);x.c.localStorage.setItem('ashwiniWishlist_1','[1]');const api=x.c.api;let lose=true;x.c.api=async(url,...args)=>{const v=await api(url,...args);if(url.endsWith('/mutate')&&lose){lose=false;throw Error('lost reply')}return v};assert.equal(await x.c.loadWishlistForCurrentUser(),false);mutateWishlist(d,1,operation(1,false));assert.equal(await x.c.loadWishlistForCurrentUser(),true);assert.deepEqual(wishlistState(d,1).items,[])});
test('local storage failure never claims a successful save',async()=>{const x=client(database());x.c.localStorage.setItem=()=>{throw Error('blocked')};assert.equal(await x.c.setWishlistItem(1,true),false)});

const transfers=source.slice(source.indexOf('async function addWishlist('),source.indexOf('async function removeWishlist('));
test('move to wishlist retains cart when wishlist save fails',async()=>{const c={user:{id:1},cart:[{id:1,size:'M',quantity:1}],canChangeShopping:()=>true,setWishlistItem:async()=>false,cartView(){},toast(){},commitShopping:async()=>assert.fail('cart must not change')};vm.createContext(c);vm.runInContext(transfers,c);await c.addWishlist(1,0,'M');assert.equal(c.cart.length,1)});
test('move to cart retains wishlist when cart save fails',async()=>{const c={user:{id:1},cart:[],canChangeShopping:()=>true,api:async()=>[{id:1,size_options:'M'}],changeCartProduct:async()=>false,setWishlistItem:async()=>assert.fail('wishlist must not change'),toast(){}};vm.createContext(c);vm.runInContext(transfers,c);await c.addWishlistToCart(1)});
