const columns=['sr_order_id','sr_shipment_id','sr_awb','sr_courier','sr_status','sr_label_url','sr_booking_state','sr_error','sr_pickup_date','sr_pickup_token','sr_destination'];
export function installReturnCourierSchema(db){for(const c of columns){if(!db.prepare('PRAGMA table_info(returns)').all().some(x=>x.name===c))db.exec(`ALTER TABLE returns ADD COLUMN ${c} TEXT NOT NULL DEFAULT ''`)}db.exec('CREATE TABLE IF NOT EXISTS return_courier_events(event_hash TEXT PRIMARY KEY,return_id INTEGER NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP)')}
export function returnCourierLinked(r){return Boolean(r.sr_order_id||r.sr_shipment_id||r.sr_booking_state)}
export function returnPayload(r,o,items,destination,now=new Date()){
 const phone=v=>String(v||'').replace(/\D/g,'').slice(-10),required=(v,name)=>{if(!String(v||'').trim())throw Error(name+' is missing');return String(v).trim()};
 const address=(prefix,x)=>{const pin=required(x.pin,prefix+' PIN'),mobile=phone(x.phone);if(!/^\d{6}$/.test(pin)||mobile.length!==10)throw Error(prefix+' needs a valid PIN and mobile number');return {[prefix+'_customer_name']:required(x.name,prefix+' name'),[prefix+'_last_name']:'',[prefix+'_address']:required(x.address,prefix+' address'),[prefix+'_city']:required(x.city,prefix+' city'),[prefix+'_state']:required(x.state,prefix+' state'),[prefix+'_country']:'India',[prefix+'_pincode']:pin,[prefix+'_phone']:mobile,[prefix+'_email']:required(x.email,prefix+' email'),[prefix+'_isd_code']:'91'}};
 if(o.status!=='DELIVERED')throw Error('Original order must be delivered before booking a return');
 if(!items.length)throw Error('Return items are missing');
 const measure=(v,f)=>Number(v)>0?Number(v):f;
 const body={order_id:`ASH-RET-${r.id}`,order_date:now.toISOString().slice(0,10),...address('pickup',{name:o.delivery_name||o.customer_name,address:o.delivery_address_line,city:o.delivery_city,state:o.delivery_state,pin:o.delivery_pincode,phone:o.customer_phone,email:o.customer_email}),...address('shipping',destination),order_items:items.map(x=>{if(!(Number(x.quantity)>0)||!(Number(x.unit_price)>=0))throw Error('Invalid return item');return {sku:`ASH-${x.product_id}-${x.size}`,name:x.name||`Product ${x.product_id}`,units:Number(x.quantity),selling_price:Number(x.unit_price),discount:0}}),payment_method:'PREPAID',total_discount:0,sub_total:items.reduce((n,x)=>n+Number(x.unit_price)*Number(x.quantity),0),weight:measure(o.shipment_weight_kg,items.reduce((n,x)=>n+measure(x.packed_weight_kg,.5)*x.quantity,0)),length:measure(o.shipment_length_cm,Math.max(...items.map(x=>measure(x.packed_length_cm,25)))),breadth:measure(o.shipment_breadth_cm,Math.max(...items.map(x=>measure(x.packed_breadth_cm,20)))),height:measure(o.shipment_height_cm,items.reduce((n,x)=>n+measure(x.packed_height_cm,5)*x.quantity,0)),request_pickup:true};return body;
}
export function secureLabel(value){try{const u=new URL(value);return u.protocol==='https:'?u.href:''}catch{return ''}}
export function returnTarget(raw,current){const s=String(raw||'').toUpperCase().replace(/[^A-Z0-9]+/g,'_').replace(/^_|_$/g,'');const map={RETURN_PICKUP_GENERATED:'PICKUP_SCHEDULED',PICKUP_SCHEDULED:'PICKUP_SCHEDULED',RETURN_PICKUP_SCHEDULED:'PICKUP_SCHEDULED',RETURN_PICKUP_RESCHEDULED:'PICKUP_SCHEDULED',MANIFESTED:'PICKUP_SCHEDULED',PICKUP_ATTEMPTED:'PICKUP_ATTEMPTED',RETURN_PICKUP_ATTEMPTED:'PICKUP_ATTEMPTED',PICKED_UP:'PICKED_UP',PICKED:'PICKED_UP',RETURN_PICKED_UP:'PICKED_UP',IN_TRANSIT:'IN_TRANSIT',RETURN_IN_TRANSIT:'IN_TRANSIT',SHIPPED:'IN_TRANSIT',OUT_FOR_DELIVERY:'IN_TRANSIT',DELIVERED:'RECEIVED',RETURN_DELIVERED:'RECEIVED',RETURN_RECEIVED:'RECEIVED'};const ranks={APPROVED:0,PICKUP_SCHEDULED:1,PICKUP_ATTEMPTED:2,PICKED_UP:3,IN_TRANSIT:4,RECEIVED:5};if(['CANCELED','CANCELLED','RETURN_CANCELED','RETURN_CANCELLED'].includes(s)&&['APPROVED','PICKUP_SCHEDULED','PICKUP_ATTEMPTED'].includes(current))return 'CANCELLED';return ranks[map[s]]>ranks[current]?map[s]:current}
export function applyReturnWebhook(db,payload,eventHash,addEvent){const awb=String(payload.awb||payload.awb_code||payload.tracking_number||'').trim(),shipment=String(payload.shipment_id||payload.sr_shipment_id||'').trim(),order=String(payload.sr_order_id||payload.shiprocket_order_id||'').trim();const matches=db.prepare("SELECT * FROM returns WHERE (sr_awb=? AND sr_awb<>'') OR (sr_shipment_id=? AND sr_shipment_id<>'') OR (sr_order_id=? AND sr_order_id<>'')").all(awb,shipment,order);if(!matches.length)return false;if(matches.length!==1)throw Error('Ambiguous return shipment identifiers');const r=matches[0];if((awb&&r.sr_awb&&awb!==r.sr_awb)||(shipment&&r.sr_shipment_id&&shipment!==r.sr_shipment_id)||(order&&r.sr_order_id&&order!==r.sr_order_id))throw Error('Return shipment identifiers disagree');
 db.exec('SAVEPOINT return_courier_event');try{if(db.prepare('INSERT OR IGNORE INTO return_courier_events(event_hash,return_id) VALUES(?,?)').run(eventHash,r.id).changes){const raw=String(payload.current_status||payload.shipment_status||payload.status||'').slice(0,100),next=returnTarget(raw,r.status);db.prepare("UPDATE returns SET status=?,sr_status=?,sr_pickup_date=COALESCE(NULLIF(?,''),sr_pickup_date),updated_at=CURRENT_TIMESTAMP WHERE id=?").run(next,raw,String(payload.pickup_scheduled_date||'').slice(0,100),r.id);if(next!==r.status)addEvent(r.id,r.user_id,next,'Return courier update',`Return #${r.id}: ${next.replaceAll('_',' ')}`)}db.exec('RELEASE return_courier_event')}catch(e){db.exec('ROLLBACK TO return_courier_event');db.exec('RELEASE return_courier_event');throw e}return true;
}
export function createReturnCourierService({db,request,addEvent}){
 const read=id=>db.prepare('SELECT * FROM returns WHERE id=?').get(id);
 async function book(id,payload){let r=read(id);if(!r||r.status!=='APPROVED')throw Error('Approve the return before booking');if(r.sr_booking_state==='CONFIRMED')return r;if(returnCourierLinked(r))throw Error('Return booking already exists or needs review. Check Shiprocket using reference ASH-RET-'+id+' before another booking.');const claim=db.prepare("UPDATE returns SET sr_booking_state='REQUESTING',sr_destination=?,sr_error='' WHERE id=? AND status='APPROVED' AND sr_booking_state='' AND sr_order_id='' AND sr_shipment_id=''").run(JSON.stringify({name:payload.shipping_customer_name,address:payload.shipping_address,city:payload.shipping_city,state:payload.shipping_state,pin:payload.shipping_pincode}),id);if(!claim.changes)throw Error('Return booking is already in progress');
 let result;try{result=await request('/shipments/create/return-shipment',{method:'POST',body:payload})}catch(e){db.prepare("UPDATE returns SET sr_booking_state='UNKNOWN',sr_error=? WHERE id=?").run(String(e.message).slice(0,500),id);throw Error('Return booking response is unconfirmed. Check ASH-RET-'+id+' in Shiprocket before retrying. '+e.message)}
 const p=result?.payload||{},confirmed=Number(result?.status)===1&&Number(p.pickup_generated)===1&&p.awb_code&&p.shipment_id&&p.order_id,state=confirmed?'CONFIRMED':'REVIEW';db.prepare("UPDATE returns SET sr_order_id=?,sr_shipment_id=?,sr_awb=?,sr_courier=?,sr_pickup_date=?,sr_pickup_token=?,sr_label_url=?,sr_booking_state=?,sr_error=?,status=CASE WHEN ?='CONFIRMED' THEN 'PICKUP_SCHEDULED' ELSE status END,pickup_at=CASE WHEN ?='CONFIRMED' THEN ? ELSE pickup_at END,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(String(p.order_id||''),String(p.shipment_id||''),String(p.awb_code||''),String(p.courier_name||''),String(p.pickup_scheduled_date||''),String(p.pickup_token_number||''),secureLabel(p.label_url),state,confirmed?'':String(result.message||'Booking partially completed; review in Shiprocket').slice(0,500),state,state,String(p.pickup_scheduled_date||''),id);
 if(confirmed)addEvent(id,r.user_id,'PICKUP_SCHEDULED','Return pickup scheduled',`Return #${id} pickup scheduled${p.pickup_scheduled_date?' for '+p.pickup_scheduled_date:''}.`);else throw Error('Return booking needs review in Shiprocket. Saved shipment details have been retained; do not create a duplicate.');return read(id);
 }
 async function label(id){const r=read(id);if(!r||!r.sr_shipment_id||!r.sr_awb||r.status==='CANCELLED')throw Error('A booked return AWB is required');if(r.sr_label_url)return secureLabel(r.sr_label_url);const result=await request('/courier/generate/label',{method:'POST',body:{shipment_id:[Number(r.sr_shipment_id)]}}),url=secureLabel(result.label_url||result.response?.data?.label_url||result.data?.label_url);if(!url)throw Error('Shiprocket has not supplied a secure return label yet');db.prepare('UPDATE returns SET sr_label_url=? WHERE id=?').run(url,id);return url}
 return {book,label};
}
