export function createReturnRefundService({db,provider,addEvent=()=>{}}){
 db.exec(`CREATE TABLE IF NOT EXISTS return_refund_jobs(return_id INTEGER PRIMARY KEY,order_id INTEGER NOT NULL UNIQUE,payment_id TEXT NOT NULL DEFAULT '',amount_paise INTEGER NOT NULL,state TEXT NOT NULL,refund_id TEXT NOT NULL DEFAULT '',receipt TEXT NOT NULL UNIQUE,manual_reference TEXT NOT NULL DEFAULT '',actor_id INTEGER NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(return_id) REFERENCES returns(id),FOREIGN KEY(order_id) REFERENCES orders(id));CREATE UNIQUE INDEX IF NOT EXISTS idx_return_manual_reference ON return_refund_jobs(manual_reference) WHERE manual_reference<>'';`);
 const job=id=>db.prepare('SELECT * FROM return_refund_jobs WHERE return_id=?').get(id);
 function eligible(id){const r=db.prepare('SELECT * FROM returns WHERE id=?').get(id);if(!r||r.request_type!=='RETURN_REFUND')throw Error('Refund return not found');if(r.status!=='INSPECTION_PASSED')throw Error('Receive and pass inspection before refunding');const o=db.prepare('SELECT * FROM orders WHERE id=?').get(r.order_id);if(!o||o.status!=='DELIVERED'||o.payment_status!=='PAID')throw Error('The delivered order must have confirmed payment before refunding');if(o.refund_status||db.prepare('SELECT refund_id FROM razorpay_refunds WHERE order_id=? LIMIT 1').get(o.id))throw Error('An existing refund needs review before another refund can be started');const amount=Math.round(Number(o.total)*100);if(!Number.isSafeInteger(amount)||amount<=0)throw Error('Invalid refund amount');return {r,o,amount}}
 function view(r,admin=false){const j=job(r.id);return {...r,return_refund_state:j?.state||'',return_refund_amount_paise:j?.amount_paise||0,...(admin?{return_refund_reference:j?.refund_id||j?.manual_reference||'',return_refund_receipt:j?.receipt||''}:{})}}
 function apply(entity){
  const j=db.prepare("SELECT * FROM return_refund_jobs WHERE (refund_id=? AND refund_id<>'') OR receipt=?").get(String(entity?.id||''),String(entity?.receipt||''));if(!j)return false;
  if((entity.receipt&&entity.receipt!==j.receipt)||!entity.id||entity.payment_id!==j.payment_id||Number(entity.amount)!==j.amount_paise||String(entity.currency).toUpperCase()!=='INR'||(j.refund_id&&entity.id!==j.refund_id))throw Error('Refund confirmation does not match the return payment/amount');
  const state=String(entity.status||'').toUpperCase();if(!['PENDING','PROCESSED','FAILED'].includes(state))throw Error('Unrecognised refund status');
  db.transaction(()=>{
   const latest=job(j.return_id);if(latest.state==='PROCESSED')return;
   const changed=latest.state!==state;
   db.prepare('UPDATE return_refund_jobs SET state=?,refund_id=?,updated_at=CURRENT_TIMESTAMP WHERE return_id=?').run(state,entity.id,j.return_id);
   db.prepare(`INSERT INTO razorpay_refunds(refund_id,order_id,payment_id,amount_paise,status) VALUES(?,?,?,?,?) ON CONFLICT(refund_id) DO UPDATE SET status=CASE WHEN razorpay_refunds.status='PROCESSED' THEN 'PROCESSED' ELSE excluded.status END,updated_at=CURRENT_TIMESTAMP`).run(entity.id,j.order_id,j.payment_id,j.amount_paise,state);
   db.prepare("UPDATE orders SET razorpay_refund_id=?,refund_status=?,refund_amount=?,payment_status=CASE WHEN payment_status IN ('DISPUTED','DISPUTE_LOST') THEN payment_status ELSE ? END,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(entity.id,state,state==='PROCESSED'?j.amount_paise/100:0,state==='PROCESSED'?'REFUNDED':state==='FAILED'?'REFUND_FAILED':'REFUND_PENDING',j.order_id);
   const r=db.prepare('SELECT * FROM returns WHERE id=?').get(j.return_id);
   if(state==='PROCESSED')db.prepare("UPDATE returns SET status='COMPLETED',updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='INSPECTION_PASSED'").run(j.return_id);
   if(changed)addEvent(r.id,r.user_id,state==='PROCESSED'?'COMPLETED':r.status,state==='PROCESSED'?'Refund processed':state==='FAILED'?'Refund failed':'Refund pending',state==='PROCESSED'?`Razorpay confirmed your refund of Rs ${j.amount_paise/100} to the original payment method. Bank credit time may vary.`:state==='FAILED'?'Refund failed. Ashwini will review it.':'Refund requested. Payment provider confirmation is pending.');
  })();return true;
 }
 async function start(id,actor){
  const existing=job(id);if(existing)return existing;
  if(!provider)throw Error('Razorpay refund service is not configured');
  const j=db.transaction(()=>{const {r,o,amount}=eligible(id);if(o.payment_method!=='RAZORPAY'||!o.razorpay_payment_id)throw Error('COD requires a separate transfer and manual refund record');db.prepare("INSERT INTO return_refund_jobs(return_id,order_id,payment_id,amount_paise,state,receipt,actor_id) VALUES(?,?,?,?,'REQUESTING',?,?)").run(id,o.id,o.razorpay_payment_id,amount,`ASH-RET-REF-${id}`,actor);db.prepare("UPDATE orders SET refund_status='PROCESSING',refund_requested_at=CURRENT_TIMESTAMP WHERE id=?").run(o.id);return job(id)})();
  try{const entity=await provider.refund(j.payment_id,{amount:j.amount_paise,speed:'normal',receipt:j.receipt,notes:{ashwini_return_id:String(id),ashwini_order_id:String(j.order_id)}});if(!apply(entity))throw Error('Missing refund reference')}catch(e){db.prepare("UPDATE return_refund_jobs SET state='UNKNOWN',updated_at=CURRENT_TIMESTAMP WHERE return_id=? AND state='REQUESTING'").run(id);db.prepare("UPDATE orders SET refund_status='UNKNOWN' WHERE id=? AND refund_status='PROCESSING'").run(j.order_id);throw Error('Refund confirmation is unclear. Use Sync Refund and check Razorpay before any further payout.');}
  return job(id);
 }
 async function sync(id){const j=job(id);if(!j)throw Error('No refund request exists');if(['PROCESSED','MANUAL_RECORDED'].includes(j.state))return j;if(!provider)throw Error('Razorpay is not configured');if(j.refund_id)apply(await provider.fetchRefund(j.payment_id,j.refund_id));else{let found=null;for(let skip=0;skip<10000;skip+=100){const page=await provider.fetchMultipleRefund(j.payment_id,{count:100,skip});if(!Array.isArray(page.items))throw Error('Invalid refund lookup response');const matches=page.items.filter(x=>x.receipt===j.receipt);if(matches.length>1||found&&matches.length)throw Error('Multiple matching refunds require provider review');if(matches.length)found=matches[0];if(page.items.length<100)break;if(skip===9900)throw Error('Refund lookup needs provider review');}if(!found)throw Error('Refund not confirmed yet. Check Razorpay; do not send another payout.');apply(found)}return job(id)}
 function manual(id,actor,reference){reference=String(reference||'').trim();if(reference.length<6||reference.length>100)throw Error('Enter the completed bank/UPI transfer reference (6–100 characters)');return db.transaction(()=>{const old=job(id);if(old){if(old.state==='MANUAL_RECORDED'&&old.manual_reference===reference)return old;throw Error('A refund record already exists')};const {r,o,amount}=eligible(id);if(o.payment_method!=='COD')throw Error('Online payments must use the Razorpay refund flow');db.prepare("INSERT INTO return_refund_jobs(return_id,order_id,amount_paise,state,receipt,manual_reference,actor_id) VALUES(?,?,?,'MANUAL_RECORDED',?,?,?)").run(id,o.id,amount,`ASH-RET-REF-${id}`,reference,actor);db.prepare("UPDATE orders SET refund_status='MANUAL_RECORDED',payment_status='REFUNDED',refund_amount=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(amount/100,o.id);db.prepare("UPDATE returns SET status='COMPLETED',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(id);addEvent(id,r.user_id,'COMPLETED','Refund recorded by Ashwini',`Ashwini recorded a refund transfer of Rs ${amount/100}. Contact support if it has not arrived.`);return job(id)})()}
 return {job,view,start,sync,manual,apply};
}
